In [61]:
import torch

In [62]:
print(torch.__version__)

2.9.0+cu126

In [63]:
import pandas as pd 
import numpy as np

In [64]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [65]:
df.head(2)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.8,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.6,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.9,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.8,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN

In [66]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

scaler = StandardScaler()

In [67]:
df.shape

(569, 33)

In [68]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [69]:
df.head(2)

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.8,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.6,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.9,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.8,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   diagnosis                569 non-null    object
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  569 non-null    float64
 15  smoothness_se            569 non-null    float64
 16  compactness_se           569 non-null    float64
 17  concavity_se             569 non-null    float64
 18  concave points_se        569 non-null    float64
 19  symmetry_se              569 non-null    float64
 20  fractal_dimension_se     569 non-null    float64
 21  radius_worst             569 non-null    float64
 22  texture_worst            569 non-null    float64
 23  perimeter_worst          569 non-null    float64
 24  area_worst               569 non-null    float64
 25  smoothness_worst         569 non-null    float64
 26  compactness_worst        569 non-null    float64
 27  concavity_worst          569 non-null    float64
 28  concave points_worst     569 non-null    float64
 29  symmetry_worst           569 non-null    float64
 30  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30), object(1)
memory usage: 137.9+ KB

In [71]:
X_train,X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

In [72]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [73]:
X_train

array([[-0.19306109, -0.63625018, -0.22176209, ..., -0.37340563,
        -1.36043214, -0.43901241],
       [-0.67398919, -0.68741476, -0.66057326, ..., -0.24502328,
        -0.15699474, -0.22390611],
       [-0.67114346,  1.23590823, -0.62417798, ...,  0.25577526,
        -0.15858659,  0.83315669],
       ...,
       [-0.87603591, -0.44787151, -0.81608032, ...,  0.63463357,
        -0.57724272,  0.59523608],
       [-0.52885704, -1.3572056 , -0.51209709, ..., -0.49473232,
         0.90158446,  0.43716554],
       [-0.34673043, -0.78974392, -0.35452211, ..., -0.24993157,
         0.16455864, -0.344496  ]])

In [74]:
y_train

124    B
488    B
537    B
499    M
322    B
      ..
389    M
505    B
440    B
130    B
475    B
Name: diagnosis, Length: 455, dtype: object

In [75]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [76]:
y_train

array([0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0])

In [77]:
y_test

array([0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0])

In [78]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

Defining the Model

In [87]:
class mySimpleNN():
    def __init__(self,X):
        self.weights = torch.rand(X.shape[1],1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1,dtype=torch.float64, requires_grad=True)

    def forward(self,X): 
        # wx + b 
        z = torch.matmul(X,self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred 
    
    def loss(self,y_pred,y):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred,epsilon, 1-epsilon)

        loss_function = -(y_train_tensor * torch.log(y_pred) + (1- y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss_function

Important Prameters

In [97]:
learning_rate = 0.1
epochs = 25

Trainig Pipeline

In [89]:
model = mySimpleNN(X_train_tensor)
print(model.weights)
print(model.bias)

tensor([[0.0849],
        [0.8044],
        [0.6713],
        [0.6811],
        [0.0637],
        [0.2574],
        [0.0443],
        [0.0113],
        [0.9818],
        [0.8297],
        [0.5630],
        [0.9094],
        [0.0513],
        [0.7288],
        [0.2213],
        [0.4215],
        [0.6385],
        [0.7448],
        [0.6109],
        [0.0730],
        [0.7219],
        [0.3813],
        [0.1495],
        [0.3562],
        [0.7563],
        [0.9411],
        [0.4251],
        [0.6283],
        [0.4312],
        [0.6902]], dtype=torch.float64, requires_grad=True)
tensor([0.], dtype=torch.float64, requires_grad=True)

In [99]:
# create model
model = mySimpleNN(X_train_tensor)

# define loop 
for epoch in range(epochs):
    # forward pass 
    y_pred = model.forward(X_train_tensor)
    
    # loss calculate
    loss = model.loss(y_pred, y_train_tensor) 
    # backward pass
    loss.backward()

    # parameter update 
    with torch.no_grad():
        model.weights -= learning_rate*model.weights.grad
        model.bias -= learning_rate*model.bias.grad

    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()    

    print(f"Epoch : {epoch +1}, Loss : {loss.item()}")

Epoch : 1, Loss : 3.5788138917093866
Epoch : 2, Loss : 3.4516082438234603
Epoch : 3, Loss : 3.325009663120013
Epoch : 4, Loss : 3.1965828303669688
Epoch : 5, Loss : 3.0614090686979196
Epoch : 6, Loss : 2.9272801298653204
Epoch : 7, Loss : 2.78948205508091
Epoch : 8, Loss : 2.644265458814423
Epoch : 9, Loss : 2.4966973180228575
Epoch : 10, Loss : 2.350228000970211
Epoch : 11, Loss : 2.2052393495731355
Epoch : 12, Loss : 2.0605302083841237
Epoch : 13, Loss : 1.9176913509894997
Epoch : 14, Loss : 1.7764132731504032
Epoch : 15, Loss : 1.6431834003304828
Epoch : 16, Loss : 1.5173672546946677
Epoch : 17, Loss : 1.401900946243756
Epoch : 18, Loss : 1.295996475699935
Epoch : 19, Loss : 1.2034973739101633
Epoch : 20, Loss : 1.124596147920988
Epoch : 21, Loss : 1.0588069161508349
Epoch : 22, Loss : 1.0049215788525367
Epoch : 23, Loss : 0.9612125779970401
Epoch : 24, Loss : 0.9257793450968504
Epoch : 25, Loss : 0.896846651595278

In [105]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy : {accuracy}")

Accuracy : 0.5880270600318909